# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setMinimumSize(QtCore.QSize(150, 30))
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.kernelSizeSlider = QtWidgets.QSlider(self.centralwidget)
        self.kernelSizeSlider.setMinimum(3)
        self.kernelSizeSlider.setMaximum(51)
        self.kernelSizeSlider.setSingleStep(2)
        self.kernelSizeSlider.setPageStep(10)
        self.kernelSizeSlider.setProperty("value", 5)
        self.kernelSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kernelSizeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.kernelSizeSlider.setTickInterval(10)
        self.kernelSizeSlider.setObjectName("kernelSizeSlider")
        self.horizontalLayout.addWidget(self.kernelSizeSlider)
        self.kernelSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.kernelSizeLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.kernelSizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kernelSizeLabel.setStyleSheet("background-color: #f0f0f0; border: 1px solid #ccc; border-radius: 3px; padding: 2px;")
        self.kernelSizeLabel.setObjectName("kernelSizeLabel")
        self.horizontalLayout.addWidget(self.kernelSizeLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.dockAreaContainer = QtWidgets.QWidget(self.centralwidget)
        self.dockAreaContainer.setMinimumSize(QtCore.QSize(0, 500))
        self.dockAreaContainer.setObjectName("dockAreaContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockAreaContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.dockAreaContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoadImage = QtWidgets.QAction(MainWindow)
        self.actionLoadImage.setObjectName("actionLoadImage")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoadImage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Свертка изображений с RGB ядром на GPU"))
        self.loadButton.setText(_translate("MainWindow", "Загрузить изображение"))
        self.label.setText(_translate("MainWindow", "Размер ядра:"))
        self.kernelSizeLabel.setText(_translate("MainWindow", "5"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь"))
        self.actionLoadImage.setText(_translate("MainWindow", "Загрузить изображение"))
        self.actionLoadImage.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "О программе"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
